name: Deploy to GitHub Pages (docs folder)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: |
          npm install
          npm install recharts

      - name: Build React app
        run: npm run build
        env:
          CI: false
          
      - name: Move build to docs folder
        run: |
          rm -rf docs
          mkdir -p docs
          mv build/* docs/
          
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Update docs folder for GitHub Pages" || echo "No changes to commit"
          git push
